from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(552, 440)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.mainTabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.mainTabWidget.setObjectName("mainTabWidget")
        self.tabRoom = QtWidgets.QWidget()
        self.tabRoom.setObjectName("tabRoom")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tabRoom)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.groupBoxIpAddress = QtWidgets.QGroupBox(self.tabRoom)
        self.groupBoxIpAddress.setObjectName("groupBoxIpAddress")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBoxIpAddress)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEditIpAddress = QtWidgets.QLineEdit(self.groupBoxIpAddress)
        self.lineEditIpAddress.setObjectName("lineEditIpAddress")
        self.gridLayout_4.addWidget(self.lineEditIpAddress, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBoxIpAddress, 0, 0, 1, 1)
        self.groupBoxPort = QtWidgets.QGroupBox(self.tabRoom)
        self.groupBoxPort.setObjectName("groupBoxPort")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBoxPort)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lineEditPort = QtWidgets.QLineEdit(self.groupBoxPort)
        self.lineEditPort.setObjectName("lineEditPort")
        self.gridLayout_7.addWidget(self.lineEditPort, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBoxPort, 0, 1, 1, 3)
        self.buttonConnect = QtWidgets.QPushButton(self.tabRoom)
        self.buttonConnect.setObjectName("buttonConnect")
        self.gridLayout_8.addWidget(self.buttonConnect, 0, 4, 1, 1)
        self.horizontalSeparator_2 = QtWidgets.QFrame(self.tabRoom)
        self.horizontalSeparator_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.horizontalSeparator_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.horizontalSeparator_2.setObjectName("horizontalSeparator_2")
        self.gridLayout_8.addWidget(self.horizontalSeparator_2, 1, 0, 1, 5)
        self.groupBoxUserName = QtWidgets.QGroupBox(self.tabRoom)
        self.groupBoxUserName.setObjectName("groupBoxUserName")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBoxUserName)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEditUserName = QtWidgets.QLineEdit(self.groupBoxUserName)
        self.lineEditUserName.setObjectName("lineEditUserName")
        self.gridLayout_3.addWidget(self.lineEditUserName, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBoxUserName, 2, 0, 1, 5)
        self.horizontalSeparator = QtWidgets.QFrame(self.tabRoom)
        self.horizontalSeparator.setFrameShape(QtWidgets.QFrame.HLine)
        self.horizontalSeparator.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.horizontalSeparator.setObjectName("horizontalSeparator")
        self.gridLayout_8.addWidget(self.horizontalSeparator, 3, 0, 1, 5)
        self.verticalLayoutJointRoom = QtWidgets.QVBoxLayout()
        self.verticalLayoutJointRoom.setObjectName("verticalLayoutJointRoom")
        self.scrollAreaChatRoomList = QtWidgets.QScrollArea(self.tabRoom)
        self.scrollAreaChatRoomList.setWidgetResizable(True)
        self.scrollAreaChatRoomList.setObjectName("scrollAreaChatRoomList")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 309, 96))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        # self.radioChatRoomName = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_2)
        # self.radioChatRoomName.setObjectName("radioChatRoomName")
        # self.gridLayout_6.addWidget(self.radioChatRoomName, 0, 0, 1, 1)
        # self.labelChatRoomActivePeople = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        # self.labelChatRoomActivePeople.setStyleSheet("color: rgb(85, 170, 0);")
        # self.labelChatRoomActivePeople.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        # self.labelChatRoomActivePeople.setObjectName("labelChatRoomActivePeople")
        # self.gridLayout_6.addWidget(self.labelChatRoomActivePeople, 0, 1, 1, 1)
        # self.labelChatRoomActivePeople_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        # self.labelChatRoomActivePeople_2.setStyleSheet("color: rgb(85, 170, 0);")
        # self.labelChatRoomActivePeople_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        # self.labelChatRoomActivePeople_2.setObjectName("labelChatRoomActivePeople_2")
        # self.gridLayout_6.addWidget(self.labelChatRoomActivePeople_2, 1, 1, 1, 1)
        # self.radioChatRoomName_3 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_2)
        # self.radioChatRoomName_3.setObjectName("radioChatRoomName_3")
        # self.gridLayout_6.addWidget(self.radioChatRoomName_3, 2, 0, 1, 1)
        # self.radioChatRoomName_2 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_2)
        # self.radioChatRoomName_2.setObjectName("radioChatRoomName_2")
        # self.gridLayout_6.addWidget(self.radioChatRoomName_2, 1, 0, 1, 1)
        # self.labelChatRoomActivePeople_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        # self.labelChatRoomActivePeople_3.setStyleSheet("color: rgb(85, 170, 0);")
        # self.labelChatRoomActivePeople_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        # self.labelChatRoomActivePeople_3.setObjectName("labelChatRoomActivePeople_3")
        # self.gridLayout_6.addWidget(self.labelChatRoomActivePeople_3, 2, 1, 1, 1)
        self.scrollAreaChatRoomList.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayoutJointRoom.addWidget(self.scrollAreaChatRoomList)
        self.buttonJoinRoom = QtWidgets.QPushButton(self.tabRoom)
        self.buttonJoinRoom.setObjectName("buttonJoinRoom")
        self.verticalLayoutJointRoom.addWidget(self.buttonJoinRoom)
        self.gridLayout_8.addLayout(self.verticalLayoutJointRoom, 4, 0, 1, 2)
        self.verticalSeparator = QtWidgets.QFrame(self.tabRoom)
        self.verticalSeparator.setFrameShape(QtWidgets.QFrame.VLine)
        self.verticalSeparator.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.verticalSeparator.setObjectName("verticalSeparator")
        self.gridLayout_8.addWidget(self.verticalSeparator, 4, 2, 1, 1)
        self.verticalLayoutCreateRoom = QtWidgets.QVBoxLayout()
        self.verticalLayoutCreateRoom.setObjectName("verticalLayoutCreateRoom")
        self.groupBoxChatRoomName = QtWidgets.QGroupBox(self.tabRoom)
        self.groupBoxChatRoomName.setObjectName("groupBoxChatRoomName")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBoxChatRoomName)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lineEditChatRoomName = QtWidgets.QLineEdit(self.groupBoxChatRoomName)
        self.lineEditChatRoomName.setObjectName("lineEditChatRoomName")
        self.gridLayout_5.addWidget(self.lineEditChatRoomName, 0, 0, 1, 1)
        self.verticalLayoutCreateRoom.addWidget(self.groupBoxChatRoomName)
        self.buttonCreateRoom = QtWidgets.QPushButton(self.tabRoom)
        self.buttonCreateRoom.setObjectName("buttonCreateRoom")
        self.verticalLayoutCreateRoom.addWidget(self.buttonCreateRoom)
        self.gridLayout_8.addLayout(self.verticalLayoutCreateRoom, 4, 3, 1, 2)
        self.mainTabWidget.addTab(self.tabRoom, "")
        self.tabChat = QtWidgets.QWidget()
        self.tabChat.setObjectName("tabChat")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tabChat)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelChatRoomName = QtWidgets.QLabel(self.tabChat)
        self.labelChatRoomName.setAlignment(QtCore.Qt.AlignCenter)
        self.labelChatRoomName.setObjectName("labelChatRoomName")
        self.gridLayout_2.addWidget(self.labelChatRoomName, 0, 0, 2, 1)
        self.labelPeopleInRoom = QtWidgets.QLabel(self.tabChat)
        self.labelPeopleInRoom.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPeopleInRoom.setObjectName("labelPeopleInRoom")
        self.gridLayout_2.addWidget(self.labelPeopleInRoom, 0, 1, 1, 1)
        self.labelPeopleInRoomName = QtWidgets.QLabel(self.tabChat)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPeopleInRoomName.sizePolicy().hasHeightForWidth())
        self.labelPeopleInRoomName.setSizePolicy(sizePolicy)
        self.labelPeopleInRoomName.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelPeopleInRoomName.setObjectName("labelPeopleInRoomName")
        self.gridLayout_2.addWidget(self.labelPeopleInRoomName, 1, 1, 2, 1)
        self.scrollAreaChatContent = QtWidgets.QScrollArea(self.tabChat)
        self.scrollAreaChatContent.setWidgetResizable(True)
        self.scrollAreaChatContent.setObjectName("scrollAreaChatContent")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 379, 194))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.labelChatContent = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelChatContent.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelChatContent.setObjectName("labelChatContent")
        self.gridLayout.addWidget(self.labelChatContent, 0, 0, 1, 1)
        self.scrollAreaChatContent.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollAreaChatContent, 2, 0, 1, 1)
        self.lineEditMessage = QtWidgets.QLineEdit(self.tabChat)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditMessage.sizePolicy().hasHeightForWidth())
        self.lineEditMessage.setSizePolicy(sizePolicy)
        self.lineEditMessage.setObjectName("lineEditMessage")
        self.gridLayout_2.addWidget(self.lineEditMessage, 3, 0, 1, 1)
        self.buttonSendMessage = QtWidgets.QPushButton(self.tabChat)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonSendMessage.sizePolicy().hasHeightForWidth())
        self.buttonSendMessage.setSizePolicy(sizePolicy)
        self.buttonSendMessage.setObjectName("buttonSendMessage")
        self.gridLayout_2.addWidget(self.buttonSendMessage, 3, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(439, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 4, 0, 1, 1)
        self.buttonExitRoom = QtWidgets.QPushButton(self.tabChat)
        self.buttonExitRoom.setStyleSheet("")
        self.buttonExitRoom.setObjectName("buttonExitRoom")
        self.gridLayout_2.addWidget(self.buttonExitRoom, 4, 1, 1, 1)
        self.mainTabWidget.addTab(self.tabChat, "")
        self.gridLayout_9.addWidget(self.mainTabWidget, 0, 0, 1, 1)
        self.labelNumberUsingApp = QtWidgets.QLabel(self.centralwidget)
        self.labelNumberUsingApp.setTextFormat(QtCore.Qt.RichText)
        self.labelNumberUsingApp.setObjectName("labelNumberUsingApp")
        self.gridLayout_9.addWidget(self.labelNumberUsingApp, 1, 0, 1, 1)
        self.buttonHelp = QtWidgets.QPushButton(self.centralwidget)
        self.buttonHelp.setStyleSheet("")
        self.buttonHelp.setObjectName("buttonHelp")
        self.gridLayout_9.addWidget(self.buttonHelp, 2, 0, 1, 1)


        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 552, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.mainTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Network Programming Chat Room "))
        # self.radioChatRoomName.setText(_translate("MainWindow", "Chat room 1"))
        # self.labelChatRoomActivePeople.setText(_translate("MainWindow", "3 in room"))
        # self.labelChatRoomActivePeople_2.setText(_translate("MainWindow", "1 in room"))
        # self.radioChatRoomName_3.setText(_translate("MainWindow", "Chat room 3 "))
        # self.radioChatRoomName_2.setText(_translate("MainWindow", "Chat room 2"))
        # self.labelChatRoomActivePeople_3.setText(_translate("MainWindow", "1 in room"))
        self.groupBoxUserName.setTitle(_translate("MainWindow", "Name"))
        # self.lineEditUserName.setText(_translate("MainWindow", "Me"))
        self.groupBoxIpAddress.setTitle(_translate("MainWindow", "IP Adress"))
        self.lineEditIpAddress.setText(_translate("MainWindow", "127.0.0.1"))
        self.groupBoxPort.setTitle(_translate("MainWindow", "Port"))
        self.lineEditPort.setText(_translate("MainWindow", "1080"))
        self.buttonConnect.setText(_translate("MainWindow", "Connect"))
        self.groupBoxChatRoomName.setTitle(_translate("MainWindow", "Chat Room Name"))
        # self.lineEditChatRoomName.setText(_translate("MainWindow", "New Chat Room"))
        self.buttonJoinRoom.setText(_translate("MainWindow", "Join Room"))
        self.buttonCreateRoom.setText(_translate("MainWindow", "Create Room"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tabRoom), _translate("MainWindow", "Rooms"))
        # self.labelChatRoomName.setText(_translate("MainWindow", "Room\'s Name"))
        # self.labelPeopleInRoom.setText(_translate("MainWindow", "People in room"))
        # self.labelPeopleInRoomName.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Client_1</span></p><p><span style=\" font-weight:600;\">Client_2</span></p><p><span style=\" font-weight:600; color:#ff0000;\">Me</span></p><p><span style=\" font-weight:600;\"><br/></span></p></body></html>"))
        # self.labelChatContent.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Client_1:</span> Hello</p><p><span style=\" font-weight:600;\">Client_2:</span> Nice to meet you</p><p align=\"right\"><span style=\" font-weight:600; color:#ff0000;\">Me:</span><span style=\" color:#ff0000;\"> Hello guys </span></p><p><span style=\" font-weight:600;\">Client_2:</span> Is this a chat room?</p><p><span style=\" font-weight:600;\">Client_1:</span> Yeah.</p><p><br/></p></body></html>"))
        self.buttonSendMessage.setText(_translate("MainWindow", "Send"))
        self.buttonExitRoom.setText(_translate("MainWindow", "Exit Chat"))
        self.buttonHelp.setText(_translate("MainWindow", "Help and Manual"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tabChat), _translate("MainWindow", "Chat"))
        # self.labelNumberUsingApp.setText(_translate("MainWindow", "<html><head/><body><p>Currently: <span style=\" color:#ff0000;\">5</span> people using app</p></body></html>"))
